name: SecurityScorecard Slack Notification

on:
  schedule:
    # 4pm UTC on first Monday of each month
    - cron: '0 16 */100,1-7 * MON'
  workflow_dispatch: # handy to trigger workflow manually. See: docs.github.com/en/actions/using-workflows/manually-running-a-workflow

jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - name: Grab grade
        id: grab_grade
        run: |
          # update the following line with your company's domain name
          domain="github.com"
          grade=$(curl -s "https://securityscorecard.com/security-rating/$domain"|grep -oh "\"grade\":\"[A-Z]\""|cut -d \" -f4)
          echo "GRADE=$grade" >> "$GITHUB_OUTPUT"
          echo "DOMAIN=$domain" >> "$GITHUB_OUTPUT"
      - name: Post grade to Slack
        env:
          GRADE: ${{ steps.grab_grade.outputs.GRADE }}
          DOMAIN: ${{ steps.grab_grade.outputs.DOMAIN }}
        run: >-
          if echo $GRADE|grep -oh [A-F];then
            response="$(curl -s -H 'Content-Type: application/json' -X POST -d '{"grade":"'$GRADE'","domain":"'$DOMAIN'"}' --url '${{ secrets.SLACK_WEBHOOK }}')"
            if [ "$response" = "{\"ok\":true}" ]; then
              exit 0
            else
              exit 1
            fi
          fi
